services:

  ldap:
    build: .
    image: milux/ctldap:latest
    restart: unless-stopped
    ports:
      - "1389:1389"
    networks:
      - ldap
    env_file:
      - ./.env

  test:
    build: test
    image: milux/ctldap:test
    restart: "no"
    networks:
      - ldap
    environment:
      - LDAP_USER
      - LDAP_PW
      - LDAP_PORT
      - LDAP_BASE_DN
    profiles:
      - test

networks:
  ldap:
